#!/usr/bin/env python3
"""
Regenerate src/lib/films.js from the films in public/media/films,
measuring each one's size and duration with ffmpeg.

    python3 scripts/media/gen-films.py

Every film whose slug doesn't start with `elf-` is marked as an excerpt.
Needs ffmpeg on PATH or FFMPEG=/path/to/ffmpeg.
"""
import os, re, subprocess
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
D = os.path.join(ROOT, 'public', 'media', 'films')
FF = os.environ.get('FFMPEG', 'ffmpeg')
rows = []
for f in sorted(os.listdir(D)):
    if not f.endswith('.mp4') or '.part' in f: continue
    slug = f[:-4]
    o = subprocess.run([FF, '-hide_banner', '-i', os.path.join(D, f)], capture_output=True, text=True).stderr
    w, h = map(int, re.search(r'Video: .*?, (\d{3,4})x(\d{3,4})', o).groups())
    hh, mm, ss = re.search(r'Duration: ([\d:.]+)', o).group(1).split(':')
    dur = round(int(hh) * 3600 + int(mm) * 60 + float(ss), 1)
    rows.append(f"  '{slug}': film('{slug}', {w}, {h}, {dur}{', true' if not slug.startswith('elf-') else ''}),")
js = '''/**
 * GENERATED by scripts/media/gen-films.py — films in /public/media/films
 * with measured sizes. Regenerate after adding or re-encoding a film.
 */
const url = (path) => `${import.meta.env.BASE_URL}media/${path}`

const film = (slug, w, h, duration, excerpt = false) => ({
  src: url(`films/${slug}.mp4`),
  poster: url(`films/${slug}-poster.webp`),
  w,
  h,
  duration,
  excerpt,
})

export const FILM = {
''' + '\n'.join(rows) + '\n}\n'
open(os.path.join(ROOT, 'src', 'lib', 'films.js'), 'w').write(js)
print(len(rows), 'films')
